### ISSUE TITLE
Auto-completion of methods returning impl Trait fails

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust-enhanced#119]
When I have a method like:
```rust
	pub fn sub_triangles<'a>(&'a self) -> impl Iterator<Item=Triangle<V>> + 'a {
		self.0.iter().enumerate().map(move |(i, &cur_i)| { let i = i as isize; [at(&self.0, i-1), cur_i, at(&self.0, i+1)] })
	}
```
and I try to auto-complete its name somewhere in the code by writing self.sub + Ctrl-Space, it expands to:
```
self.sub_triangles   Function (poly.rs) : pub fn sub_triangles<'a>(&'a self) -> impl Iterator<Item=Triangle<V>> + 'a
```
I also had this issue with another method returning impl Trait so I think that triggers this.

**Comment by dten** [comment]
@boscop this plugin doesn't do anything about auto complete

https://github.com/phildawes/racer does the suggestions and https://github.com/defuz/RustAutoComplete adds it to sublime

**Comment by dten** [comment]
Hmm unless this is the simple scope based expansions going wrong?

**Comment by ehuss** [comment]
I suspect this is an issue with another plugin, so closing for now.
