### ISSUE TITLE
Can't find crate for dev-dependencies while rustc has no problems!

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust-enhanced#171]
| System or Software | Version |
|--|--:|
| Sublime Text | Build 3126 |
| Rust Enhanced | 1.2.3 |

An image for the problem:
http://i.imgur.com/PK5nSVr.png

I experience this problem in my crate "prophet" at [this](https://github.com/Robbepop/prophet/blob/master/src/lib.rs#L77) position.
The crate `approx` is my only dev-dependency. Maybe this has something to do with the false-positive error?

rustc and cargo do have no problems at all and everything compiles fine even without warnings.

**Comment by ehuss** [comment]
For now, you can set `rust_syntax_checking_include_tests` to false in your `RustEnhanced.sublime-settings`.   I'm not entirely sure why it fails, I will look into it more.

**Comment by ehuss** [comment]
There's not much that can be done about this for now (other than disable checking of test code as mentioned above).  Running "cargo rustc" will not pull in dev-dependencies, and I don't see a way to force it.  "cargo check" doesn't check test code either (see rust-lang/cargo#3431).

**Comment by Robbepop** [comment]
Thank you very much for the info!

**Comment by Jayflux** [comment]
Can this ticket be closed?

**Comment by ehuss** [comment]
> Can this ticket be closed?

I'd prefer to leave it open until checking of tests is fixed.  I recently added support for `cargo check` to validate test code (Rust 1.23, with `--profile test`).  However, I haven't updated Rust Enhanced to take advantage of this, yet.  I'll try to work on it soon, since I find it annoying when tests don't get checked.
