### ISSUE TITLE
Instance of rustc persisting after quitting sublime, and also taking up 100% CPU.

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust-enhanced#203]
### Sublime Text Version
Sublime Text 3 (Build 3126) Stable Channel

### Rust Enhanced Version
2.1.0

### Operating system
macOS 10.12.1 Sierra.

### Expected behavior
All rustc's should quit when I exit sublime. Also, none of them should take up 100% CPU for very long.

### Actual behavior
When I save a rust file, I often end up with a single thread rustc that is taking up 100% of a core. No amount of waiting seems to calm it down (it's sometimes taken over a day before I notice this), and it persists after quitting sublime -- even more, if i quit and reopen sublime, I can end up with more than one. This happens basically every time the first time I save a rust file after opening sublime.

I've removed all the other rust plugins I had, and I can still repro. When it's kicked off it usually says stuff like "Rust syntax check running...", and the console has something like `Syntax Check +269.667 Rust running: ['cargo', 'metadata', '--no-deps']`. The "Rust syntax check running..." never really appears to go away. That I've noticed, at least.

My rustc version is 1.19.0. Let me know if you need more info. 

### Steps to reproduce
1. Open a file in a rust project. It seems to require a cargo.toml file or it will say it's skipping the syntax check, which avoids the problem.
2. Save.
3. Check activity monitor and notice rustc at 100%
4. Quit Sublime
5. rustc stays, and stays at 100%. 

Repeating these steps just leads to more rustc's.

### References

Here's [a process sample](https://irccloud.mozilla.com/pastebin/fsf9eMHT/) I asked about in IRC. 

I've looked through my sublime preferences for rust and all of them seem to be blank, or I'd attach the files. (If you still want to see my pref files, that's not a problem, just LMK which ones).

**Comment by ehuss** [comment]
Does this happen with a basic project ("hello world", no dependencies), or is it unique to your project?

Does the Sublime command "Rust Cancel Build" stop it?  (This command is bound to Ctrl-C on OS X if the current view is a Rust source file.)

I'll look into killing rust when exiting Sublime.  I'll also look into adding better debugging support, it's pretty minimal right now.

**Comment by thomcc** [comment]
Sorry for never getting back on this, but it does seem to be fixed now.
