### ISSUE TITLE
Add 'continue' and 'break' to keyword/autocomplete list

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/rust-enhanced#214]

**Comment by dten** [comment]
Could you elaborate?

`continue` and `break` are already keywords, and this package doesn't do autocomplete
https://github.com/rust-lang/sublime-rust/blob/master/RustEnhanced.sublime-syntax#L127

**Comment by RazrFalcon** [comment]
Well, when I'm typing `for` I'm getting a `for ... in ... { ... }` tooltip. I thought that it's this plugin feature, not `racer`. And it will be useful to see the same tooltip for `continue` and `break`.

**Comment by dten** [comment]
I see. `for` comes from a snippet, i wouldn't call it auto-complete
https://github.com/rust-lang/sublime-rust/blob/master/snippets/for.sublime-snippet

they're normally for providing more than a single word completion, i.e. the `for` one prepares space for variable, range and some brackets. Feels a bit odd to just have `continue` type the word `continue`. I don't see other languages in sublime providing that

**Comment by RazrFalcon** [comment]
I don't know about sublime, but Qt Creator do this for C++. So it's feels natural for me.

**Comment by dten** [comment]
if you add a snippet i suspect it would get merged

**Comment by dten** [comment]
These are a thing now if someone wants to close this
