### ISSUE TITLE
Syntax highlighting fails with custom operators

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust-enhanced#219]
When using the [mdo crate](https://github.com/TeXitoi/rust-mdo), which uses the custom `=<<` operator, syntax highlighting fails / looks ugly:

![](https://image.prntscr.com/image/0-9_GTY0T2OEtRKVLfbseQ.png)

Also it fails in this case:
![](https://image.prntscr.com/image/x1x-CcLoQwexl-tJ6kEUBQ.png)

And in cases like this:
![](https://image.prntscr.com/image/2EGhMFgWTAWJ8087MajV9w.png)

**Comment by dten** [comment]
I have a fix for the top one but the fact that macros can contain almost anything causes quite a few problems.
I already have syntax PRs #215 and #217 waiting to merge and this fix doesn't merge nicely with them
haven't seen @Jayflux in a while to merge anything

**Comment by ehuss** [comment]
Yea, I've noticed that the highlighting has a lot of difficulty with macros.  I'm curious @dten if you have any ideas on what to do about that.  There seems to be a tension between macros allowing anything vs the desire to still reasonably highlight valid Rust expressions within a macro.  

The related problem I've run into is `forward_to_deserialize` from serde breaks highlighting for several lines after the macro (for example when it has the keyword `struct` within it).

I'm wondering if macros could just use a very simplified syntax that would still look reasonable in the common use cases.

**Comment by Boscop** [comment]
Maybe it can parse things like `=<<` just like normal operators?

**Comment by dten** [comment]
But it isn't an operator 🙁
In the PR it thinks it's twon operators. It only broke because it was trying to handle some other complex macro case

**Comment by Jayflux** [comment]
Free this weekend, will take a look

**Comment by Jayflux** [comment]
@dten do you have permissions to merge?

**Comment by dten** [comment]
I do not
