### ISSUE TITLE
Hard to read messages with darker theme.

### ISSUE THREAD

**Issue by ergose** [rust-lang/rust-enhanced#231]
**Sublime Text:** 3 (Build 3143)
**Rust Enhanced:** v2.4.0
**OS Name:** ElementaryOS 
**OS Version:** Loki 0.4.1/Ubuntu 16.04.2 LTS

### What should have happened?
Darker background to inline errors/warnings/notes/help when used with darker theme.
A config file switch to set the background maybe grey vs white.

### What actually happened?
Yellow text on White, Red text on White, etc. Can barely read them.
Config file was unclear how to change background to darker color (if it even can be set in the config file for this.) Referenced minihtml wasn't clear either in context with the enhancement settings.

### Steps to reproduce
Unsure. Using 'Material Theme' v4.1.2 with 'Material-Theme-Darker', but assuming any dark theme may have this issue with this module. I saw the note in config for rust-enhanced to see the minihtml reference, but didn't really know what to do with it. If it can be done in that config file, I feel the issue is that an example is not in the config file. I'd rather not have to edit a base theme for inline errors created by this. I'd rather override it in this config.

As a workaround, I tried turning off inline, but then can't get to message due to #229. 

My ideal for this module would be where I could select which message types to show inline and which in gutter with hover, as well as a dark background option for inline. I like the errors inline, but not so much the warnings. I would also open a feature request for mixed inline and gutter for different message types, but I'm busy so trying to wrap this up. Excellent work though on the module. Getting instant feedback inline from Rust is really helping me learn it quicker.

**Comment by ehuss** [comment]
Material Theme is ([maybe?](https://github.com/equinusocio/material-theme/pull/1217)) [no longer supported](https://github.com/equinusocio/material-theme/commit/4dcecf409d6a4489bf5a4d9487854d6017f41569), and has some bugs with the most recent Sublime.  It looks like the Darker theme is not working correctly.  [This commit](https://github.com/equinusocio/material-theme/commit/9f6caac30240f026c64ab98a1f80ba2d54476a89) may fix the problem, but a new release has not been made.

Although it may be a good idea to add more color options, you might want to find a better supported scheme.  Alternatively, you could try copying the scheme from the above commit into your User directory and switching to that.

**Comment by ehuss** [comment]
Closing for now, this appears to be an issue with another package
