### ISSUE TITLE
Enable AutoComplete for ::

### ISSUE THREAD

**Issue by Jayflux** [rust-lang/rust-enhanced#232]
### Sublime Text Version
Sublime Text 3 (Build 3156)

### Rust Enhanced Version
v2.5.0

### Operating system
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393

### Expected behavior
Now LSP uses RLS, we should see auto completions when importing a module
Here is an example from VSCode
![vscode_example](https://user-images.githubusercontent.com/936006/34204752-c3217c26-e577-11e7-9256-07fff375ad7e.gif)

### Actual behavior
after typing :: nothing happens, this should show auto completions (from RLS right now)

Here's an example
![rls_autocomplete](https://user-images.githubusercontent.com/936006/34204675-7dc6fb24-e577-11e7-8699-fc43f5895c69.gif)
### Steps to reproduce
This has previously been fixed manually in https://github.com/tomv564/LSP/issues/212#issuecomment-352911378 can this be added to the package so users don't have to do this themselves?
Are there any ramifications to doing this?

### References
https://github.com/tomv564/LSP/issues/212#issuecomment-352911378

**Comment by ehuss** [comment]
I think it should be safe to add those autocomplete triggers.  I've had them in my Rust settings for a long time without any noticeable issues.

**Comment by Jayflux** [comment]
This was fixed in the latest release
