### ISSUE TITLE
Case sensitivity in syntax highlighting

### ISSUE THREAD

**Issue by ghlecl** [rust-lang/rust-enhanced#238]
Hello,

Probably low on the priority list, but I am using the name `Std` in an Enum like so:
``` rust
#[derive(Debug)]
enum BeamMode {
   Std,
   FFF
}
```
and the syntax highlighter picks up `Std` as a language word or crate name or something (probably because of std modules) and so colors it.  I don't know if it's simply because syntax highlighting is not case sensitive and should be or if it's expected behavior.  I just thought I would report it.  I personally think it should not pick it up and remain uncolored (or main text colored), but it's just my preference.

Hoping this explanation makes sense.  If not, let me know.

In any case, thanks for the package.  :-)

### Sublime Text Version
Sublime Text 3 (Build 3156)

### Rust Enhanced Version
2.6.0

### Operating system
macOS 10.12.6

**Comment by ehuss** [comment]
I don't think it has anything to do with it being "Std" specifically.  All identifiers in CamelCase are treated as a type identifier.  Identifiers in all upper case (like "FFF") are treated as a constant.

**Comment by ghlecl** [comment]
You are absolutely right.  So sorry to have bothered you.  It is indeed the opposite.  The FFF is identified as a constant which is why it is rendered as not highlighted.  The opposite of what I had originally thought.

Thanks for the info and sorry again for having bothered you with that.

**Comment by dten** [comment]
so this should be closed?

**Comment by ghlecl** [comment]
I thing so.  Sorry.
