### ISSUE TITLE
Isn't it better to always run clippy from a nightly channel?

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust-enhanced#249]
`cargo +nightly clippy` instead of `cargo clippy`. And revert it back when (if) clippy will be available on stable.

Am I missing something?

**Comment by ehuss** [comment]
I changed the default to nightly as a side effect in #246, though that hasn't been merged, yet.

There are a couple workarounds.

In your `RustEnhanced.sublime-settings`, you can add:
```json
{
    "cargo_build":
    {
        "variants":
        {
            "clippy": {
                "toolchain": "nightly"
            }
        }
    }
}
```

Or, if you set up your environment variables correctly, Clippy can work on stable.  It depends on your platform and your setup.  
* Windows: Make sure `%USERPROFILE%\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin` is in your `PATH`.
* Mac: Make sure `~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib` is in `LD_LIBRARY_PATH`.
* Linux: I think is similar to the Mac approach.

**Comment by pravic** [comment]
Oh, thanks for workarounds. Settings look good.

**Comment by ehuss** [comment]
I think this can be closed, clippy should be defaulting to nightly now.

**Comment by pravic** [comment]
Yes, [it is](https://github.com/rust-lang/rust-enhanced/blob/761796f5b67f4ebc98c3318ef982bddc8a2823f2/rust/cargo_settings.py#L128-L134).
