### ISSUE TITLE
Rust enhanced not found in package control

### ISSUE THREAD

**Issue by paupav** [rust-lang/rust-enhanced#254]
### Sublime Text Version
E.g Sublime Text 3 (Build 3143)

### Rust Enhanced Version
none

### Operating system
A good example is:
OS Name	elementaryOS
Version	0.4.1

### Expected behavior
rust-enhanced in package control

### Actual behavior
rust-enhanced is not in package control

### Steps to reproduce
..

### References
None

I've tried adding github repo, doesn't work.
On package controls website there is yellow question mark saying that PackageInfo is missing.

**Comment by ehuss** [comment]
I filed an issue with wbond/package_control#1334.

**Comment by paupav** [comment]
But also manually adding github repo didn't work for me.

**Comment by ehuss** [comment]
It looks like Package Control is back on its feet, so I think this can be closed.
