### ISSUE TITLE
There was an error trying to build, RLS features will be limited. Try running `cargo check` for more information.

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-enhanced#255]
### Sublime Text Version
Sublime Text 3 (Build 3157)

### Rust Enhanced Version
2.8.0

### Operating system
10.13.4 Beta (17E150f)

### Expected behavior
I should be able to type without frequent interruption

### Actual behavior
An error "There was an error trying to build, RLS features will be limited. Try running `cargo check` for more information." pops up every  <img width="400" src="https://user-images.githubusercontent.com/72159/36663163-959ee2de-1ad8-11e8-889f-7c0c9793ac72.png" alt="[error]"> few seconds <img width="400" src="https://user-images.githubusercontent.com/72159/36663163-959ee2de-1ad8-11e8-889f-7c0c9793ac72.png" alt="[error]"> and it just keeps <img width="400" src="https://user-images.githubusercontent.com/72159/36663163-959ee2de-1ad8-11e8-889f-7c0c9793ac72.png" alt="[error]"> 
coming back and <img width="400" src="https://user-images.githubusercontent.com/72159/36663163-959ee2de-1ad8-11e8-889f-7c0c9793ac72.png" alt="[error]"> won't go away, no matter <img width="400" src="https://user-images.githubusercontent.com/72159/36663163-959ee2de-1ad8-11e8-889f-7c0c9793ac72.png" alt="[error]"> how many times I <img width="400" src="https://user-images.githubusercontent.com/72159/36663163-959ee2de-1ad8-11e8-889f-7c0c9793ac72.png" alt="[error]"> click it.

Please don't report it more than once, or use the console or the status bar to show it. I *know* my build is broken, but I struggle to fix it with sublime being constantly inter<img width="400" src="https://user-images.githubusercontent.com/72159/36663163-959ee2de-1ad8-11e8-889f-7c0c9793ac72.png" alt="[error]">rupted.

### Steps to reproduce
1. Half-configure broken RLS
2. Try to use Sublime

**Comment by urschrei** [comment]
Are you also using LSP?

**Comment by kornelski** [comment]
Yes. I've followed instructions in the readme to install RLS+LSP.

**Comment by urschrei** [comment]
In that case, I suspect the problem is LSP, not Rust-Enhanced, since Rust-Enhanced doesn't interact with RLS in any way.

**Comment by kornelski** [comment]
I see. Thank you for looking into this.
