### ISSUE TITLE
Feature Request (Improvement)

### ISSUE THREAD

**Issue by gurpreetshanky** [rust-lang/rust-enhanced#275]
### Operating system
Microsoft Windows 10 Pro

### Expected behavior
Should only print errors.

### Actual behavior
Prints all paths in terminal.

When running rust run and if there are some errors, then Rust enhanced prints all the paths on Windows which makes difficult to analyse errors.
![2018-05-04 00_56_01-groove music](https://user-images.githubusercontent.com/26076066/39613563-1a13cc32-4f36-11e8-995f-fc8f4953aad6.png)

Or is there any some setting to disable that?

**Comment by TheIronBorn** [comment]
You're asking specifically about the `[path: C:\...` portion of the output?

**Comment by gurpreetshanky** [comment]
@TheIronBorn Yes. In other build systems in Sublime I can configure it to hide it.

**Comment by dten** [comment]
That comes from sublime's exec module and I didn't think it's configurable. Which systems can you configure it?

**Comment by gurpreetshanky** [comment]
@dten First See this answer. [https://stackoverflow.com/questions/36611270/how-to-remove-the-windows-path-from-a-sublime-text-3-python-build-error]. If I use my own build systems like for Python editing lines in exec.py hides the path but it doesn't work with Rust Enhanced.

**Comment by ehuss** [comment]
Yea, it seems like a good idea to make this configurable.  I've been planning to add a debug logging facility (particularly for the on-save checking which currently suppresses all output).  I'm wondering if maybe this could be tied into that.
