### ISSUE TITLE
"Accept Replacement" bugs

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang/rust-enhanced#276]
Thanks for the Accept Replacement feature!  It's already been really useful.

However, I am finding bugs where clicking the button does nothing. The button doesn't disappear.

### Sublime Text Version
Sublime Text 3 (Build 3170)

### Rust Enhanced Version
2.11.0

### Operating system
macOS 10.13.4

**Comment by TheIronBorn** [comment]
It might just be that the button doesn't work until Clippy is finished with its work in the rest of the crate

**Comment by ehuss** [comment]
Ah, I see what's wrong.  The replacement code needs to fetch the region from Sublime, but the regions aren't available until the compilation is finished.  I think the regions can be added earlier, though.  There's currently some code to try to handle overlapping regions to ensure they get the right color, but I don't think it works terribly well (in the past I've noticed Sublime is kinda random on which one appears on top).
