### ISSUE TITLE
conflicts with rustfmt plugin

### ISSUE THREAD

**Issue by berkus** [rust-lang/rust-enhanced#277]
### Sublime Text Version

Sublime Text 3 (Build 3175)

### Rust Enhanced Version

v2.11.0

### Operating system

macOS High Sierra (10.13.4)

### Expected behavior

Rustfmt continues to format files on save

### Actual behavior

Rustfmt doesnt't run on save (probably file type mismatch?)

### Steps to reproduce
1. Disable Sublime's "Rust" package
2. Enable "Rust Enhanced"
3. Enable RLS
4. Install and enable "Rustfmt"
5. Ensure "format_on_save" in Rustfmt config is set to `true`
6. Open rs file and switch format to "Rust Enhanced" (for some reason it cannot detect automatically)
7. Make changes and save file - no reformatting is applied.

**Comment by jasonwilliams** [comment]
Thanks for this @berkus I agree, I think the best option would be to move rust formatting into this package

**Comment by ehuss** [comment]
Rustfmt seems to work fine for me.  I suspect whatever issue you have in #278 is causing your issue here.

**Comment by berkus** [comment]
Indeed, #278 started working somehow and then the Rustfmt also got working.

I suspect it was some detection machinery broken internally in Sublime and some caches got flushed making it working again.

**Comment by berkus** [comment]
I opened #279 to track the option move.
