### ISSUE TITLE
Configuration loading errors/warnings

### ISSUE THREAD

**Issue by berkus** [rust-lang/rust-enhanced#278]
### Sublime Text Version

Sublime Text 3 (Build 3175)

### Rust Enhanced Version

v2.11.0

### Operating system

macOS High Sierra (10.13.4)

### Expected behavior

Load without issues.

### Actual behavior

Warnings printed on plugin startup.

### Steps to reproduce
1. install Rust Enhanced
2. restart Sublime Text

```
no such context type-any-identifiers at line 840 column 16 in Packages/Rust Enhanced/RustEnhanced.sublime-syntax
no such context type-any-identifiers at line 833 column 20 in Packages/Rust Enhanced/RustEnhanced.sublime-syntax
Packages/Rust Enhanced/RustEnhanced.sublime-syntax: context 07dc2a51a46712e099f4f5be2f3d22dd::impl-generic has a scope name, but is unreachable, so the name will never be used
```

Not sure if this is related or harmless, but automatic detection of Rust files does not work. All .rs files open as Plain Text by default.

**Comment by ehuss** [comment]
> automatic detection of Rust files does not work. All .rs files open as Plain Text by default.

It should switch automatically, I can't reproduce that.  Make sure the `extensions` aren't somehow set in the settings (View > Syntax > Open all with current extension as.. > Rust Enhanced > Rust Enhanced).

The warnings should be eventually fixed, but they shouldn't be getting in the way of syntax highlighting.

**Comment by berkus** [comment]
Weird, but it just started working by itself. Just to be sure made assignment to Rust Ehnanced through `View`>`Syntax`>`Open all...` menu.

**Comment by berkus** [comment]
Ok, I believe I know the reason.

When using a project/workspace in sublime, the editor seems to _cache_ the language plugin setting for all open files.

So when you disable Rust without closing all .rs files already open in the workspace - they get stuck with the old type information. Even though View>Syntax>Open all with this extension is pointing at Rust Enhanced, this setting is not applied until you close and reopen the .rs file again.

Not sure if this is fixable on the plugin side.

**Comment by ehuss** [comment]
I think I have seen that.  It should be fixable (it can iterate over open views after installation and adjust the syntax based on extension).

**Comment by berkus** [comment]
Should I open a separate feature request for that?

**Comment by ehuss** [comment]
@berkus Sure!  Something along the lines "Open Rust views do not automatically switch syntax after installation", I'll know what it means. :smile:
