### ISSUE TITLE
cargo check in Sublime fails with `failed to parse process output`

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust-enhanced#310]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
2.14.0

### Operating system
Win 8.1

### Expected behavior
Cargo check succeeds

### Actual behavior
Cargo check fails with:
```
error: Could not compile `webui`.

Caused by:
  failed to parse process output: `rustc --crate-name webui webui\src\lib.rs --error-format json --crate-type lib --emit=dep-info,metadata -C opt-level=1 -C debuginfo=2 -C debug-assertions=on -C metadata=a7d78831c2f9743b -C extra-filename=-a7d78831c2f9743b --out-dir D:\projects\myproject\target\debug\deps -C incremental=D:\projects\myproject\target\debug\incremental -L dependency=D:\projects\myproject\target\debug\deps --extern smart_default=D:\projects\myproject\target\debug\deps\smart_default-416f190130a4d8aa.dll --extern ws=D:\projects\myproject\target\debug\deps\libws-1a9195936cbadad5.rmeta --extern core_types=D:\projects\myproject\target\debug\deps\libcore_types-8a673881bab0fecb.rmeta --extern serde_json=D:\projects\myproject\target\debug\deps\libserde_json-5e1d6d30cb1f0efd.rmeta --extern rust_embed=D:\projects\myproject\target\debug\deps\rust_embed-3fd0e714e6d3ac54.dll --extern actix_web=D:\projects\myproject\target\debug\deps\libactix_web-4f9b4cb315e92cf7.rmeta --extern fps_loop=D:\projects\myproject\target\debug\deps\libfps_loop-74a746eab5748f54.rmeta --extern serde=D:\projects\myproject\target\debug\deps\libserde-c0d24b9498a8d3cd.rmeta --extern log=D:\projects\myproject\target\debug\deps\liblog-60a2a125a3f77050.rmeta --extern serde_derive=D:\projects\myproject\target\debug\deps\serde_derive-4486def9305cd24b.dll --extern actix=D:\projects\myproject\target\debug\deps\libactix-4e9a194f7f637239.rmeta -Ctarget-feature=+crt-static -Ctarget-cpu=haswell -L native=D:\Program Files\Microsoft Visual Studio 14.0\VC\atlmfc\lib\amd64 -L native=D:\projects\myproject\target\debug\build\brotli-sys-09fc316d500702b8\out -L native=D:\projects\myproject\target\debug\build\ring-8a153ed7e036b822\out -L native=D:\Program Files\Microsoft Visual Studio 14.0\VC\atlmfc\lib\amd64 -L native=D:\projects\myproject\target\debug\build\miniz-sys-d8e4d5bc924dd6f2\out` (exit code: 0)
```

Why does `cargo check` fail only in Sublime?
It works fine outside.
This only happens when I use the [`rust-embed`](https://github.com/pyros2097/rust-embed) crate and have this code:
```rust
#[derive(RustEmbed)] 
#[folder = "../frontend/static/"] 
struct Assets;
```
Btw, this causes the generated code to use `include_bytes!()` for each file in that dir, but how could that cause a failure to parse the cargo output? 

Which part fails to parse the output? Does rust-enhanced fail to parse cargo's output? Or does cargo fail to parse rustc's output?

If I try to do `cargo check` in cmd.exe outside of sublime, it works..

rustc 1.27.0-nightly (565235ee7 2018-05-07)

**Comment by ehuss** [comment]
Looks like it's a bug in `rust-embed`.  It [prints to stdout](https://github.com/pyros2097/rust-embed/blob/2025bfb7b8becb4f281efa5cd3febc611ba98fcb/src/lib.rs#L56) during compilation.  Macros should not do that.  It causes cargo to fail when used with `--message-format=json`.  I'd suggest bringing the issue up with them.

**Comment by Boscop** [comment]
Ah yes. But the printing only happens with `--release`, right? Why does `cargo check` fail then? :)

**Comment by Boscop** [comment]
Ah yes. But would it be ok for macros to print to stderr instead?

**Comment by ehuss** [comment]
Perhaps stderr will be better, it looks like cargo (and Rust Enhanced) ignores lines that don't start with `{`.  I still wouldn't do it (especially with ansi codes), but it should work.

**Comment by pyros2097** [comment]
Well.. I thought it would be good to see which files are being loaded into the binary at compile time. That would make it easy to find out the progress of the compilation and also if some large file is taking too long. Does printing to stderr is a better approach or removing it altogether better. Anyways I'm ok with removing the println no one else has issues with it.

**Comment by pyros2097** [comment]
But will be :sob:  as I have to remove the cool screenshots of my terminal from the readme.md

**Comment by ehuss** [comment]
Looks like this is resolved, so I'm going to close for now.
