### ISSUE TITLE
Expand macro parsing to repeated patterns

### ISSUE THREAD

**Issue by westerhack** [rust-lang/rust-enhanced#311]
### Sublime Text Version
Sublime Text 3 (Build 3176)

### Rust Enhanced Version
v2.15.0

### Operating system
macOS v10.13.4 (high sierra)

### References
Improvement number 25 on #284 is also something that should be updated

### Request
highlight repeated patterns:

```rust
macro_rules! foo {
	($($foo:expr),*) => {}
}
```

It'd be nice if `$foo:expr` would highlight as if i didn't have the `$(),*` surrounding it.

**Comment by ehuss** [comment]
I have a fix for this, I'll be posting the PR soon.
