### ISSUE TITLE
add support for `pub` within struct tuples

### ISSUE THREAD

**Issue by westerhack** [rust-lang/rust-enhanced#313]
### Sublime Text Version
Sublime Text 3 (Build 3176)

### Rust Enhanced Version
v2.15.0

### Operating system
macOS v10.13.4 (high sierra)

### Expected behavior
the `pub` should be highlighted in `struct Foo(pub String);`

### Actual behavior
It's not highlighted; however, it is within enums: 
<img width="380" alt="screen shot 2018-07-30 at 11 41 34 am" src="https://user-images.githubusercontent.com/6655027/43407775-9f5bcad8-93ed-11e8-80fc-e4a0ae92e1a0.png">

### Steps to reproduce
1. type `struct Foo(pub String)`

**Comment by ehuss** [comment]
This is fixed in `v2.16.0-prerelease`.  See https://packagecontrol.io/docs/settings for more detail on installing prereleases.  However, it shouldn't be too long for it to be released.
