### ISSUE TITLE
Please add messages to show up in status bar or a keyboard shortcut for popover option

### ISSUE THREAD

**Issue by it6** [rust-lang/rust-enhanced#339]
Is there a way to get error messages in status bar (error messages could get longer this might not be the best way to show but this is better than inline phantom messages which clutter the file)

I found the `popup` option helpful, but I wish there is a keyboard shortcut to show popup. 

I looked at the rust messages list from command palette, that gives me the entire list of errors in the current file not the one where my cursor is at.

Thanks.

**Comment by ehuss** [comment]
I've added some options in #344 to support this.  `rust_message_status_bar` will show the message under the cursor in the status bar.  You can bind the command `rust_message_popup` to a keybinding (or run it from the Command Palette) to force a popup to open for the message under the cursor.

**Comment by ehuss** [comment]
Sorry about that.  The changes weren't included in the last release.  I went ahead and made a new release ([v2.18.0](https://github.com/rust-lang/rust-enhanced/releases/tag/v2.18.0)), and it should show up there.  Let me know if you have any issues with it.

**Comment by ehuss** [comment]
I'm going to close this for now, as I think this is fixed.  Please let me know if you have any problems with the new feature.
