### ISSUE TITLE
"Error: Cannot determine Rust package to use."

### ISSUE THREAD

**Issue by Bigemul** [rust-lang/rust-enhanced#340]
### Sublime Text Version
Sublime Text 3 (Build 3176)

### Rust Enhanced Version
v2.15.0

### Operating system
macOS 10.13.6 High Sierra

### Expected behavior
I would have hoped my program to run.

### Actual behavior
I get a message:

<img width="532" alt="screen shot 2018-08-29 at 00 20 14" src="https://user-images.githubusercontent.com/31310622/44754380-df189200-ab21-11e8-9972-ebcec677c436.png">

### Steps to reproduce
1.Type
fn main() {
print!("Hello, world!");
}

2. Press cmd + shift + B
3. Clic on "RustEnhanced - Run"

### References
Are there any other GitHub issues (open or closed) that should be linked here?

I don't know. I didn't find anything related to this problem except in the rust-enhanced's source.

Thanks in advance.

**Comment by ehuss** [comment]
If you want to run rust scripts without a Cargo project, you should use [cargo script](https://github.com/DanielKeep/cargo-script).  Install that package (`cargo install cargo-script`) and then choose it as a build variant (cmd+shift+B - "RustEnhanced - Script").

**Comment by Bigemul** [comment]
Thanks a lot. It works.
