### ISSUE TITLE
Code folding on raw string with newline

### ISSUE THREAD

**Issue by jack-t** [rust-lang/rust-enhanced#353]
### Sublime Text Version
Sublime Text 3 (Build 3170)

### Rust Enhanced Version
v2.18

### Operating system
Windows Pro 1803. My Rust installation uses the Windows Subsystem for Linux, so it is not available to Rust Enhanced as far as I can tell.

### Expected behavior
Code folding: when you fold code, so long as it's valid Rust, the contents of the to-be-folded block should disappear.

### Actual behavior
When the to-be-folded code has a raw string with a newline, the code folding mechanism gets confused. The rest of the file, along with any block that includes the raw string can't be folded right. I've attached a screenshot.

![rust enhanced bug report](https://user-images.githubusercontent.com/1216435/47062411-df3d2180-d1a3-11e8-836c-c37f01054b1c.JPG)

The expected behavior, to be specific, is: the raw string should not indicate where the code block ends. I've done some searching with the Github advanced search tool, and it seems like rust-enhanced doesn't deal with code folding, but I've also found that the Sublime Text API has some support for code folding, so it may be possible to fix this issue. It may be that this bug report belongs with Sublime Text instead of this package.

### Steps to reproduce
1. Write some rust that includes a raw string with a newline.
2. Try to fold the code surrounding that string.

### References
None that I could find.

Thank you!

**Comment by jack-t** [comment]
I went looking and found this file, too: https://github.com/sublimehq/Packages/blob/master/Rust/Rust.sublime-syntax

This might be the root of the problem, in which case this issue is probably not useful. It don't understand Sublime's syntax files, but it seems like it might not account for a multi-line raw string.

**Comment by ehuss** [comment]
Thanks for the report.  Unfortunately code folding is based on indentation, and not something the per-language syntax can control.  

Coincidentally, Will just responded at https://github.com/SublimeTextIssues/Core/issues/101 that they are currently not working on folding improvements. ☹️

**Comment by jack-t** [comment]
Good to know. Thanks!
