### ISSUE TITLE
How to stop app from running

### ISSUE THREAD

**Issue by pavacicp** [rust-lang/rust-enhanced#354]
Is there a way to stop app from running when building with RustEnhanced - Run ?

### Steps to reproduce
1. Select build system rust-enhanced -run
2. try to close running server instance without closing sublime or changing build system to build
3. post your findings

**Comment by ehuss** [comment]
I'm going to close this for now.  Feel free to post any questions you have.

**Comment by bf** [comment]
Both are not working for me on linux
