### ISSUE TITLE
Recognise async keyword

### ISSUE THREAD

**Issue by jamwaffles** [rust-lang/rust-enhanced#359]
Rust recently introduced the `async` keyword for functions and impl methods, however Rust enhanced doesn't pick it up as a keyword and leaves it without any colourisation. 

### Sublime Text Version
Sublime Text 3 dev channel (Build 3185)
Aurora colour scheme

### Rust Enhanced Version
v2.18.0

### Operating system
OS Name	Linux Mint
Version	19 (Cinnamon)

### Expected behavior
When I type `async fn foo() {}`, I expect the `async` keyword to be highlighted.

### Actual behavior
The `async` keyword is left at the default font colour for the current colour scheme

![image](https://user-images.githubusercontent.com/800791/50573336-08944380-0dca-11e9-8d0c-899de72defd5.png)

![image](https://user-images.githubusercontent.com/800791/50573347-19dd5000-0dca-11e9-9774-a50c9e99fcfc.png)

### Steps to reproduce
1. Open a new buffer
2. Set syntax to `Rust Enhanced`
3. Type `async fn foo() {}`

### References
None

**Comment by lzutao** [comment]
This could be closed because we have added syntax highlighting for async keyword.
