### ISSUE TITLE
please delete, it was my mistake

### ISSUE THREAD

**Issue by ILjh7qKmc1hGaebQ8BTtX5e4FxpQEG7iB** [rust-lang/rust-enhanced#368]
Please delete this issue as I seem to be unable to. Thank you for your work!

**Comment by ehuss** [comment]
> 3126

This version of Sublime is several years old. I would suggest getting the most recent version available. It's quite likely some things won't work on such an old version.

Are there any messages in the Sublime console?

The plugin generally expects that `cargo` is in your PATH.  If you can't set PATH, you can change the `rust_env` setting in the RustEnhanced settings (there is a commented example in the settings page) to change PATH just for the plugin.  

Another thing to try is to restart Sublime.

**Comment by ILjh7qKmc1hGaebQ8BTtX5e4FxpQEG7iB** [comment]
Oh that was a mistake. I use 3176.

The console is full of `FileNotFoundError: [WinError 2] The system cannot find the file specified` in various Python files.

`cargo` is in my path and accessible via the command line.

**Comment by ILjh7qKmc1hGaebQ8BTtX5e4FxpQEG7iB** [comment]
> Another thing to try is to restart Sublime.

I am an idiot. That did the trick.. Thank you for your reply, I will try to delete this useless issue.
