### ISSUE TITLE
No need to package `tests` folder in Sublime package

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-enhanced#379]
### Sublime Text Version
Version 3.2.1, Build 3207

### Rust Enhanced Version
v2.19.0

### Operating system
All

### Expected behavior
There is no need to package `tests` folder in Sublime package.

**Benefit**: Reduce package's size.

### Actual behavior
```bash
% unzip -l Rust\ Enhanced.sublime-package |rg '\s+tests'
    21826  2019-05-16 19:27   tests/test_cargo_build.py
      540  2019-05-16 19:27   tests/README.md
     8696  2019-05-16 19:27   tests/test_interrupt.py
     2376  2019-05-16 19:27   tests/test_click_handler.py
     2468  2019-05-16 19:27   tests/test_phantom_style.py
     2062  2019-05-16 19:27   tests/test_cargo_settings.py
     3323  2019-05-16 19:27   tests/test_target_detect.py
...
```

**Comment by lzutao** [comment]
Also, we might not need `docs` folder

**Comment by ehuss** [comment]
I don't know if that's possible (I can't find a way).  If someone knows of a way to exclude folders, feel free to submit a PR!

**Comment by lzutao** [comment]
I wonder how do you release this package? Just zip it or third-party 
will do it.

**Comment by ehuss** [comment]
Just tag it. packagecontrol.io takes care of packaging/distribution.

**Comment by lzutao** [comment]
Okay. I think packagecontrol.io get this package from default GitHub release tag's zip files.
So ignore unneeded files/directories from the git archive could be the solution. In that case,
I opened #384 to do that.
