### ISSUE TITLE
Go to definition does not work for standard library

### ISSUE THREAD

**Issue by jonathan-s** [rust-lang/rust-enhanced#390]
### Sublime Text Version
Sublime Text 3 Build 3207

### Rust Enhanced Version
2.20

### Operating system
OSX 10.11

### Expected behavior
Trying to use go to definition

### Actual behavior
Unable to find ... 

### Steps to reproduce
use std::net::TcpListener;

Try to use go to defintion on the above. No success.

**Comment by ehuss** [comment]
Sorry, this isn't possible with Sublime's symbol indexing.

If you install [LSP](https://github.com/tomv564/LSP) with RLS, it should work. You'll also need to install the rust-src files.  Have you tried that?

**Comment by jonathan-s** [comment]
Yeah it works with installing RLS and LSP. Hovering over the imports let's me see where they come from.
