### ISSUE TITLE
Constant color highlighting

### ISSUE THREAD

**Issue by chrisallick** [rust-lang/rust-enhanced#398]
### Sublime Text Version
Sublime Text 3.2.1 (Build 3207)

### Rust Enhanced Version
Syntax highlighting enhancement, constant color variables highlight the color of that variable?

![Screen Shot 2019-07-22 at 10 35 08 AM](https://user-images.githubusercontent.com/378073/61652268-65732080-ac6c-11e9-8fd7-c9306f86b17d.png)

How could would it be if that were red? How would one go about implementing this? I'd be happy to take a crack.

**Comment by ehuss** [comment]
Colors are defined by your [color scheme](http://www.sublimetext.com/docs/3/color_schemes.html). There are a number of tools on packagecontrol to help create and edit them.  The scope you would want to change is `constant.other` (or `constant.other.rust` if you only want to change rust).  

If you have any other questions on working with color schemes, I suggest searching on https://forum.sublimetext.com/.

**Comment by chrisallick** [comment]
Thanks!
