### ISSUE TITLE
Goto Symbol in Project doesn't find union definitions

### ISSUE THREAD

**Issue by tommit** [rust-lang/rust-enhanced#414]
### Sublime Text Version
Sublime Text 3.2.2 (Build 3211)

### Rust Enhanced Version
2.21.0

### Operating system
macOS Catalina 10.15.1 (19B88)

### Expected behavior
**Sublime Text > Goto > Goto Symbol in Project** should find `union` definitions.

### Actual behavior
**Sublime Text > Goto > Goto Symbol in Project** doesn't find `union` definitions.

### Steps to reproduce
1. Type the following in some .rs file:
```rust
union Asdf {
    n: u64,
    f: f64,
}
```
2. Choose **Sublime Text > Goto > Goto Symbol in Project** and type "Asdf"
3. Observe that our union isn't listed in the suggested goto results

### Other observations
I noticed that **Goto Symbol in Project** starts finding union definitions if you add the text "entity.name.union.rust" to the list of items in the following files:
- RustSymbols.JSON-tmPreferences
- RustSymbols.tmPreferences

**Comment by ehuss** [comment]
Yep, was just an oversight. Updated the definition, thanks!
