### ISSUE TITLE
Ability to add extra flags to cargo run/build/whatever

### ISSUE THREAD

**Issue by CreepySkeleton** [rust-lang/rust-enhanced#422]
### Feature request

Right now, the only way to append custom CLI options to a `cargo` run is `(with args)`. Unfortunately, sublime will prepend your options with `--` which is not always desired. 

Is is possible in sublime to omit this `--`?

**Comment by ehuss** [comment]
You can customize the arguments before `--` with the `extra_cargo_args` config setting (see https://github.com/rust-lang/rust-enhanced/blob/master/docs/build.md).  You can run the Sublime command `Rust: Configure Cargo Build` to assist setting that value correctly (choose "Set Extra Cargo Arguments", and then set whether you want to set it globally or just in your project, and whether it is used for all build variants or just one).

You can also create custom build variants if you want to switch between different configurations with different options.  Use the "Rust: Create New Cargo Build Variant" to help you define a new one where you can customize these settings (see linked docs).

**Comment by CreepySkeleton** [comment]
Custom build variants would work, but I'm going to end up with a dozen of extra variants then.

`extra_cargo_args` looks good, thanks for the tip.

**Comment by alice-i-cecile** [comment]
Updated link for others who run into this: <https://doc.rust-lang.org/book/ch12-01-accepting-command-line-arguments.html>
