### ISSUE TITLE
Rust Enhanced package breaks AutoSetSyntax package

### ISSUE THREAD

**Issue by BlackDex** [rust-lang/rust-enhanced#427]
### Sublime Text Version
Sublime Text 3 (Build 3211)

### Rust Enhanced Version
v2.21.0

### Operating system
A good example is:
OS Name	Arch Linux
Version	All updates installed

### Expected behavior
Should not break AutoSetSyntax package.

### Actual behavior
Breaks AutoSetSyntax extension.

### Steps to reproduce
1. Install both Rust Enhanced and AutoSetSyntax package.
2. Check the debug console ctrl+`
3. AutoSetSyntax reports errors.

The issue is that in `Cargo.sublime-syntax` the setting `file_extensions` is just a string.
But according to Sublimetext it needs to be a list of strings. https://www.sublimetext.com/docs/3/syntax.html

When i change it from just `rs` to `['rs']` all starts working again.

**Comment by ZimbiX** [comment]
@BlackDex I just came across this myself, and have submitted [a PR with your fix](https://github.com/rust-lang/rust-enhanced/pull/429). Thanks for finding that! Out of curiosity, how did you work out that was the issue? I'm glad I didn't have to dig any deeper after, by process of elimination, determining that this package was the problem, then checking for a GitHub issue here.

**Comment by BlackDex** [comment]
@ZimbiX Well it wasn't that hard.
In the ST3 Console i noticed AutoSetSyntax produced an error, and it gave the location where in the python file. So i modified AutoSetStyntax to print the objects in the while loop there, and all printed fine without errors until it came to this package for loading the extensions its providing.

And i noticed it did this on the file_extensions, looked at ST site on how you need to define it, and it should always be an array. So changed that, and all worked out.

**Comment by ZimbiX** [comment]
@BlackDex Nice. Cheers for the info. I'll keep that in mind for next time
