### ISSUE TITLE
Update README to recommend stable rustup branch for RLS

### ISSUE THREAD

**Issue by peterkos** [rust-lang/rust-enhanced#434]
From [rust-lang/rls](https://github.com/rust-lang/rls#error-component-rls-is-unavailable-for-download-nightly):
> rls, clippy are available on the stable channel. Meaning most developers installing for the first time should use stable.

Is there a reason why the README recommends using `nightly` still for RLS? Seems to work fine (macOS+Sublime) on `stable`.

Although notably, I had to install `rust-analyzer` with `brew`; after _that_, everything worked well. 😄

**Comment by ehuss** [comment]
Thanks, the docs were just out of date.  I updated them with some new information.
