### ISSUE TITLE
Is it possible to create a sublime vintage command :Crun, :Ccheck... like in vim plugin

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-enhanced#438]
Accessing Cargo - run, check, test, build... through command palette and right-click menu was not comfortable and little confusing.

Today, I came to know that in Sublime can use vim like experience through "Vintage" mode.

Is it possible to create vim shortcut command like :Crun, :Ccheck just like in vim plugin?

Take a look at the screenshot. I feel adding this feature to the Rust Enhanced Sublime plugin will simplify a lot and boost the work flow.

![Annotation 2020-08-06 114735](https://user-images.githubusercontent.com/13760265/89497994-06327080-d7db-11ea-9d77-8cd0300f6b70.png)

**Comment by ehuss** [comment]
I'm not familiar with the Vintage mode, but I suspect it is not directly possible.

Build commands are available via the command palette.  "Build With: Rust Enhanced", or via the build selector (see https://github.com/rust-lang/rust-enhanced/blob/master/docs/build.md).  

Commands can be assigned to shortcuts, or you can define custom commands with `.sublime-commands` files.

I don't think this is something this plugin can do anything about, so I'm going to close for now.
