### ISSUE TITLE
Feature request: Limit the number of threads used

### ISSUE THREAD

**Issue by ckaran** [rust-lang/rust-enhanced#439]
This is a feature request.  Can you please put in a setting similar to `-j` to limit the number of threads used by rust-enhanced when running cargo?  I have other threads that have soft-realtime requirements that are running simultaneously, and they start to choke up whenever I save my code.  I've tested to make sure that running `cargo build --release -j 4` does the right thing, so I know that this method will work.

**Comment by ehuss** [comment]
You can set flags via the config system.  Docs are [here](https://github.com/rust-lang/rust-enhanced/blob/master/docs/build.md#cargo-settings).  For example, "Rust: Configure Cargo Build" > "Set Extra Cargo Arguments" > "...in this Sublime Project" > "before -- separator" > `-j2`.  An alternative is to set an environment variable `CARGO_BUILD_JOBS` in the config system.

**Comment by ckaran** [comment]
That seems to work, thank you!
