### ISSUE TITLE
Suggest function signature and inferred type after assignment

### ISSUE THREAD

**Issue by fgadaleta** [rust-lang/rust-enhanced#444]

**Comment by ehuss** [comment]
I believe this request is better suited for use with a language server.  You can install one with [Sublime LSP](https://packagecontrol.io/packages/LSP). It supports both [RLS](https://github.com/rust-lang/rls) and [rust-analyzer](https://rust-analyzer.github.io/).  If it isn't already supported, I would suggest seeing if there is already an issue in the [rust-analyzer issue tracker](https://github.com/rust-analyzer/rust-analyzer/issues) or file a new one.
