### ISSUE TITLE
Duplicate diagnostic navigation phantoms and ESC key binding

### ISSUE THREAD

**Issue by toyboot4e** [rust-lang/rust-enhanced#445]
### Sublime Text Version
Sublime Text 3 (Build 3211)

### Rust Enhanced Version
v2.22.0

### Operating system
OS Name	macOS
Version	10.15.6

### Problem

When I call `lsp_next_diagnostic`, there are phantoms from both Rust Enahnced (up) and Sublime LSP (down):

<img width="428" alt="Screen Shot 2020-09-17 at 17 52 38" src="https://user-images.githubusercontent.com/47905926/93448579-b8974080-f90e-11ea-9e33-1ba3dedb6d5e.png">

Then I pressed ESC:

<img width="361" alt="Screen Shot 2020-09-17 at 17 53 07" src="https://user-images.githubusercontent.com/47905926/93449059-3f4c1d80-f90f-11ea-86df-188dfea43614.png">

It only erased phantom from Rust Enhanced.

* Sublime LSP phantom has to be erased with mouse.
* We don't need Sublime LSP phantom, perferring Rust Enhanced phantoms.

### Intent

First I'm opening issue here to ask if there are better settings available. If not, I (or someone else) would make an issue in Sublime LSP like this: "Add option to disable diagnostic navigation phantoms".

### ESC shortcuts

Rust Enhanced has ESC shortcut to erase its phantom:

* [Shortcut to hide phantoms ? · Issue #200 · rust-lang/rust-enhanced](https://github.com/rust-lang/rust-enhanced/issues/200)

While Sublime LSP also has ESC shortcut to erase its phantom:

* [Show previous/next diagnostic with phantom by tomv564 · Pull Request #783 · sublimelsp/LSP](https://github.com/sublimelsp/LSP/pull/783)

I guess the former overwrote the latter (so when I pressed ESC, only Rust Enhanced phantom was removed).

**Comment by detly** [comment]
Is this (effectively) a duplicate of #332?

**Comment by toyboot4e** [comment]
@detly Yes it looks like a duplicate.
