### ISSUE TITLE
Is it possible to show the filename where the error occurs?

### ISSUE THREAD

**Issue by jd84** [rust-lang/rust-enhanced#446]
Hello,
Rust Enhanced works very well, but on larger projects I've some trouble to find the file where an error occurs. In my bottom bar Rust Enhanced only shows me that there is an error, but not the filename. I've to say I'm relying on the "check on save" function. 

![screenshot-20200922-103543](https://user-images.githubusercontent.com/48910727/93861187-682e3300-fcc0-11ea-99a4-b69653550f68.png)

Is it possible to highlight the file in the sidebar, similar to the git-plugin which will draw (in my case) a simple dot to on the files I've modified. Or at least show the file names where the error occurs in the bottom bar.

Maybe it's a setting I've missed?

Thanks for help!

**Comment by ehuss** [comment]
I normally use the Next/Previous Result shortcut keys (https://github.com/rust-lang/rust-enhanced/blob/master/docs/build.md#usage), which will jump directly to the errors or warnings.

I would think in a large project, showing an icon in the sidebar would be difficult to find.  I'm not familiar with the API for interacting with the sidebar, but if it isn't too difficult, I guess it could be an option.

**Comment by jd84** [comment]
Thanks, I didn't noticed that this exists, this helps a lot.
