### ISSUE TITLE
Completion seems to not trigger on `Ctrl`+`Space`

### ISSUE THREAD

**Issue by DrOptix** [rust-lang/rust-enhanced#460]
### Context
I'm trying to switch from VSCode to Sublime, but I have some issues with the completion/intellisense popup. For me this aspect kind of keeps me to VSCode camp.

### Sublime Text Version
3.2.2 Build 3211
![image](https://user-images.githubusercontent.com/512152/115965740-3bcae580-a533-11eb-952c-ebe3514dd2ca.png)

### Rust Enhanced Version
2.23.0
![image](https://user-images.githubusercontent.com/512152/115965781-661ca300-a533-11eb-8c22-1f044ec170e2.png)

### Operating system
Fedora 33 64bit
![image](https://user-images.githubusercontent.com/512152/115965989-3326df00-a534-11eb-97ab-259a15cdbd66.png)

### Expected behavior
Completion popup to be displayed when I press `Ctrl`+`Space`

### Actual behavior
The popup is displayed only when I start typing.

### Steps to reproduce
![rust_enhanced_completion](https://user-images.githubusercontent.com/512152/115966046-87ca5a00-a534-11eb-8bf5-8928f1dbf80e.gif)

### References
I don't know

**Comment by ehuss** [comment]
I think the default key binding for auto-completion on Linux is "alt+/". 

Also, keep in mind that Sublime's auto-completion is not by default language-aware.  The assert completions that you see are called [snippets](https://docs.sublimetext.io/guide/extensibility/snippets.html), and there are only a [small number](https://github.com/rust-lang/rust-enhanced/tree/master/snippets) defined in this package.  If you want more language aware completion, you'll need something like [LSP](https://packagecontrol.io/packages/LSP) with [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer).

**Comment by DrOptix** [comment]
I have LSP and rust-analyzer installed/

Thank you a million, why the flowers did they put `Alt + /` as a key binding I'll never understand. I thought that `Ctrl + Space` was so standard that no one would think of other finger gymnastics to replace it. Not intuitive at all.

I will close this issue and I will modify the key binding.
