### ISSUE TITLE
Function name highlight when there is space between function name and parameters

### ISSUE THREAD

**Issue by sweetyoru** [rust-lang/rust-enhanced#479]
### Sublime Text Version
Sublime Text 4 (Build 4126)

### Rust Enhanced Version
2.24.0

### Operating system
Arch Linux

### Expected behavior
The function name in a call is highlighted even when there is a space between function name and its parameters.

### Actual behavior
The function name appear in white color.

### Steps to reproduce
1. Type this line: function_name (arg1, arg2, arg2);
2. See the function name color

**Comment by ehuss** [comment]
Thanks for the report!  I posted #480 with a fix.

**Comment by TheIronBorn** [comment]
I would bet there's other legal whitespace we've been ignoring

**Comment by sweetyoru** [comment]
Maybe, method call? my_obj.something (arg1, arg2);
