### ISSUE TITLE
Error are not highlighted in-code

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [rust-lang/rust-enhanced#489]
I hate creating issues on problems local to my setup but I'm really stuck here.

Rust Enhanced is installed, Rust > Check is working perfectly displaying a list of errors in the bottom panel, debug log is clean, number of errors is correctly displayed in the status bar after saving a file, but errors are not highlighted in-code neither on-save, nor after running Rust > Check. User config is empty, global config has `"rust_syntax_checking": true` enabled.

I've disabled all the third-party packages, including SublimeLinter.

![image](https://user-images.githubusercontent.com/48632512/169717236-99980e02-c087-441e-ace5-8b46c5fb3470.png)

### Sublime Text Version
Sublime Text 3 (Build 4126)

### Rust Enhanced Version
v2.25.0

### Operating system
```bash
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"

$ uname -a
Linux ws1 5.13.0-43-generic #48-Ubuntu SMP Tue May 10 13:02:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected behavior
Errors should be highlighted in-code

### Actual behavior
Errors are not highlighted in-code

### Steps to reproduce
1. Open a Rust project
2. Introduce an intentional error in a source file
3. Save it
4. Errors are not highlighted

**Comment by ehuss** [comment]
Hm, that's strange.  Are there any errors or messages in Sublime's console (`ctrl + backtick`)?  

In the console, when a Rust file open, you can type:

```python
view.settings().get('show_errors_inline')
```

And that should verify if the setting is enabled.

Also double-check the Rust-specific config (command `Preferences: Rust Enhanced Settings`).

**Comment by s0me0ne-unkn0wn** [comment]
@ehuss console is clean also, no errors. The settings seems legit:
```
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin Rust Enhanced.cargo_build
reloading python 3.3 plugin Rust Enhanced.SyntaxCheckPlugin
reloading python 3.3 plugin Rust Enhanced.toggle_setting
reloading python 3.3 plugin SideBarFolders.OpenFilesInFolderWindow
reloading python 3.3 plugin SideBarFolders.SideBarFolders
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2022-05-22 23:17:10, next run at 2022-05-23 00:17:10 or after
>>> view.settings().get('show_errors_inline')
True
```

Going to Preferences > Package Settings > Rust Enhanced > Settings, I get two configs, a global one (which is the default, I didn't ever change anything there), and a local one, which is `{}`.

**Comment by s0me0ne-unkn0wn** [comment]
The debug log, just in case:

```
+0.000 Running: cargo metadata --no-deps
+0.040 Rust Enhanced: Failed to find target for '/home/s0me0ne/src/rust/life/src/main.rs'
+0.005 Running: rustc --version
+0.013 Running: cargo check --message-format=json --profile=test
+0.014     Checking life v0.1.0 (/array/home/s0me0ne/src/rust/life)
+0.010 error: could not compile `life` due to 2 previous errors
+0.001 On-save check finished.
```

**Comment by s0me0ne-unkn0wn** [comment]
Believe it or not, I've tried everything, and it started working after a reboot. I'm feeling a bit Windowsish right now.
