### ISSUE TITLE
Import suggestion breaks code with `#[cfg]`

### ISSUE THREAD

**Issue by marcospb19** [rust-lang/rust-enhanced#516]
### Sublime Text Version
Build 4155

### Rust Enhanced Version
2.25.0

### Operating system
Arch Linux

### Steps to reproduce

1. Add this code:
```rust
#[cfg(unix)]
use std::os::unix::fs;

fn main() {
    let _ = stdout();

    #[cfg(unix)]
    {
        // Using unix specific stuff here.
        let _function = fs::chroot::<&str>;
    }
}
```
2. Save the file.
3. Click on the suggestion to import the function.
4. Arrive at this code:
```rust
#[cfg(unix)]
use std::io::stdout;
use std::os::unix::fs;

fn main() {
...
```
5. Code should now be incompatible with non-unix platforms, because `cfg(unix)` is not on top of the `std::os::unix` import.

---

Should this be thrown to upstream as a compiler diagnostic issue? Or does it belong here, considering that `rust-enhanced` assumes `rustc` tips are trustworthy?

**Comment by ehuss** [comment]
The suggestions are generated by rustc, so this should be reported at https://github.com/rust-lang/rust/issues, thanks!
