### ISSUE TITLE
LSP not working or being loaded

### ISSUE THREAD

**Issue by drguildo** [rust-lang/rust-enhanced#531]
I've installed the package, and have the LSP package installed too, but it doesn't seem to be working correctly.

It says "Rust Enhanced" in the bottom-right corner, but that's about it. There's no docs when I mouseover a std function, and no sign that the LSP server is being run.

I haven't received any message about rust-analyzer being downloaded and no messages about my project being built either.

When I go to "Enable Language Server Globally" in the Command Palete, nothing about Rust is listed.

I've tried downloading rust-analyzer manually and putting it in my PATH, but it didn't make any difference.

**Comment by ehuss** [comment]
Sorry, I'm not able to provide support for the LSP package. You might have a little more luck asking on their issue tracker (https://github.com/sublimelsp/LSP I think), or perhaps one of the user forums.
